version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=deliveryesphera
    ports:
      - 5434:5434
    expose:
      - 5434
    networks:
      - esphera-network
  deliveryesphera:
    image: jpedrocunha/deliveryesphera
    restart: always
    working_dir: /home/jp/Documentos/Esphera/espheradelivery
    environment:
        - TZ=America/Sao_Paulo
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/deliveryesphera
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin123
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 9999:9999
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - esphera-network
networks:
  esphera-network:
    driver: bridge